package codes.vg.betterkotlinjavacompletion.dataclass

import codes.vg.betterkotlinjavacompletion.util.FilterCase
import codes.vg.betterkotlinjavacompletion.util.completionParametersAtCaret
import codes.vg.betterkotlinjavacompletion.util.lightClassMethod
import com.intellij.ide.highlighter.JavaFileType
import com.intellij.testFramework.fixtures.BasePlatformTestCase

class KotlinDataClassComponentNFilterTest : BasePlatformTestCase() {

    private lateinit var filter: KotlinDataClassComponentNFilter

    override fun setUp() {
        super.setUp()
        filter = KotlinDataClassComponentNFilter()
    }

    fun testComponentNFiltering() {
        myFixture.addFileToProject(
            "User.kt",
            """
                package codes.vg.betterkotlinjavacompletion.dataclass

                data class User(
                    val firstName: String,
                    val lastName: String,
                ) {
                    operator fun component3() = "${"$"}firstName ${"$"}lastName"
                    operator fun component4() = firstName
                }
            """.trimIndent()
        )

        myFixture.addFileToProject(
            "NotADataClass.kt",
            """
                package codes.vg.betterkotlinjavacompletion.dataclass

                class NotADataClass {
                    operator fun component1() = "not to be filtered out"
                }
            """.trimIndent()
        )

        val javaTemplate = """
            package codes.vg.betterkotlinjavacompletion.dataclass;

            class DataClassCompletionTest {
                void test(%s instance) {
                    instance.%s<caret>IntellijIdeaRulezzz
                }
            }
        """.trimIndent()

        val cases = listOf(
            FilterCase("component1", "User", true), // generated by compiler
            FilterCase("component2", "User", true), // generated by compiler
            FilterCase("component3", "User", false), // declared by user
            FilterCase("component4", "User", false), // declared by user
            FilterCase("component1", "NotADataClass", false), // declared in an ordinary class
        )

        cases.forEachIndexed { index, (methodName, className, expectedFiltered) ->
            val javaCode = javaTemplate.format(className, methodName)
            myFixture.configureByText(JavaFileType.INSTANCE, javaCode)
            val parameters = myFixture.completionParametersAtCaret()
            val method = myFixture.lightClassMethod(className, methodName)

            val isFiltered = filter.shouldFilterOut(method, parameters)

            assertEquals(
                "[$index] Unexpected filtering for $className.$methodName",
                expectedFiltered,
                isFiltered,
            )
        }
    }
}
